
exports.seed = function(knex) {
  return knex('cars').insert([
    { make:'Acura', model: 'CL', category:'COUPE', size:'M', }, 
    { make:'Acura', model: 'ILX', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'Integra', category:'COUPE', size:'S', },
    { make:'Acura', model: 'Legend', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'MDX', category:'SUV', size:'L', }, 
    { make:'Acura', model: 'NSX', category:'EXOTIC', size:'E', },
    { make:'Acura', model: 'RDX', category:'SUV', size:'L', },
    { make:'Acura', model: 'RL', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'RLX', category:'SEDAN', size:'M', }, 
    { make:'Acura', model: 'RSX', category:'COUPE', size:'S', },
    { make:'Acura', model: 'SLX', category:'SUV', size:'L', },
    { make:'Acura', model: 'TL', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'TLX', category:'SEDAN', size:'M', }, 
    { make:'Acura', model: 'TSX', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'Vigor', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'ZDX', category:'SUV', size:'L', },

    { make:'Alfa Romeo', model: '4C', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: '8C', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: '8C Competizione', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: 'C4', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: 'Giulia', category:'SEDAN', size:'L', },
    { make:'Alfa Romeo', model: 'Giulietta', category:'COUPE', size:'M', },
    { make:'Alfa Romeo', model: 'Milano', category:'SEDAN', size:'M', },
    { make:'Alfa Romeo', model: 'Spider', category:'COUPE', size:'M', },
    { make:'Alfa Romeo', model: 'Stelvio', category:'SUV', size:'L', },

    { make:'Aston Martin', model: 'DB11', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DB7', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DB9', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DBS', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DBS Superleggera', category:'COUPE', size:'E', },
    { make:'Aston Martin', model: 'DBX', category:'SUV', size:'E', },
    { make:'Aston Martin', model: 'Lagonda', category:'SEDAN', size:'L', },
    { make:'Aston Martin', model: 'One-77', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'Rapide', category:'SEDAN', size:'E', },
    { make:'Aston Martin', model: 'Valkyrie', category:'COUPE', size:'E', },
    { make:'Aston Martin', model: 'Vanquish', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'Vantage', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'Virage', category:'EXOTIC', size:'E', },

    { make:'Audi', model: '100', category:'SEDAN', size:'M', },
    { make:'Audi', model: '4000', category:'SEDAN', size:'M', },
    { make:'Audi', model: '5000', category:'SEDAN', size:'M', },
    { make:'Audi', model: '80', category:'SEDAN', size:'M', },
    { make:'Audi', model: '90', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A3', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A4', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A5', category:'COUPE', size:'M', },
    { make:'Audi', model: 'A5 Sportback', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A6', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A7', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'A8', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'Allroad', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'Cabriolet', category:'COUPE', size:'M', },
    { make:'Audi', model: 'Coupe', category:'COUPE', size:'M', },
    { make:'Audi', model: 'E-Tron Quattro', category:'SUV', size:'E', },
    { make:'Audi', model: 'Q3', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q4', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q5', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q7', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q8', category:'SUV', size:'E', },
    { make:'Audi', model: 'R8', category:'EXOTIC', size:'E', },
    { make:'Audi', model: 'RS 3', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'RS 4', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'RS 5', category:'COUPE', size:'L', },
    { make:'Audi', model: 'RS 6', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'RS 7', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S3', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S4', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S5', category:'COUPE', size:'L', },
    { make:'Audi', model: 'S6', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S7', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S8', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'SQ5', category:'SUV', size:'L', },
    { make:'Audi', model: 'TT', category:'COUPE', size:'M', },
    { make:'Audi', model: 'TT RS', category:'COUPE', size:'L', },
    { make:'Audi', model: 'TTS', category:'COUPE', size:'L', },
    { make:'Audi', model: 'V8 Quattro', category:'SEDAN', size:'M', },

    { make:'Bentley', model: 'Arnage', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Azure', category:'EXOTIC', size:'E', },
    { make:'Bentley', model: 'Bentayga', category:'SUV', size:'E', },
    { make:'Bentley', model: 'Brooklands', category:'EXOTIC', size:'E', },
    { make:'Bentley', model: 'Continental', category:'EXOTIC', size:'E', },
    { make:'Bentley', model: 'Continental GT', category:'E', size:'E', },
    { make:'Bentley', model: 'Eight', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Flying Spur', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Mulsanne', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Turbo R', category:'SEDAN', size:'E', },

    { make:'BMW', model: '128i', category:'COUPE', size:'M', },
    { make:'BMW', model: '135i', category:'COUPE', size:'M', },
    { make:'BMW', model: '135iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '228i', category:'COUPE', size:'M', },
    { make:'BMW', model: '228i xDrive', category:'COUPE', size:'M', },
    { make:'BMW', model: '230i', category:'COUPE', size:'M', },
    { make:'BMW', model: '318i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '318iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '318ti', category:'COUPE', size:'M', },
    { make:'BMW', model: '320i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '320i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '323ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '323i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '323iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '325Ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '325e', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325eS', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325i', category:'COUPE', size:'M', },
    { make:'BMW', model: '325iS', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325iX', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328 Gran Tourismo xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328 xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328Ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '328d', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328d xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '328xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '330Ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '330e', category:'SEDAN', size:'M', },
    { make:'BMW', model: '330i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '330xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335d', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335i Gran Tourismo xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '335xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '340i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '428i', category:'COUPE', size:'M', },
    { make:'BMW', model: '428i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '428i Gran Coupe xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '428i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '430i', category:'COUPE', size:'M', },
    { make:'BMW', model: '430i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '435i', category:'COUPE', size:'M', },
    { make:'BMW', model: '435i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '435i Gran Coupe xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '435i xDrive', category:'COUPE', size:'M', },
    { make:'BMW', model: '440i', category:'COUPE', size:'M', },
    { make:'BMW', model: '440i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '525i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '525xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '528i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '530i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '530xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '533i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535d', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535d xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535i Gran Tourismo', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535i Gran Tourismo xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '550i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '633CSi', category:'COUPE', size:'L', },
    { make:'BMW', model: '635CSi', category:'COUPE', size:'M', },
    { make:'BMW', model: '640i', category:'COUPE', size:'L', },
    { make:'BMW', model: '640i Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: '640i xDrive', category:'COUPE', size:'L', },
    { make:'BMW', model: '645Ci', category:'COUPE', size:'L', },
    { make:'BMW', model: '650i', category:'COUPE', size:'L', },
    { make:'BMW', model: '650i Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: '650i Gran Coupe xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '650i xDrive', category:'COUPE', size:'L', },
    { make:'BMW', model: '733i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '735i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '735iL', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740iL', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740Ld xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740Li xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '745i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '745Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750i xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750iL', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750Li xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '760i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '760Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '840Ci', category:'COUPE', size:'L', },
    { make:'BMW', model: '850Ci', category:'COUPE', size:'L', },
    { make:'BMW', model: '850CSi', category:'COUPE', size:'L', },
    { make:'BMW', model: '850i', category:'COUPE', size:'L', },
    { make:'BMW', model: 'ActiveHybrid 3', category:'SEDAN', size:'M', },
    { make:'BMW', model: 'ActiveHybrid 4', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'ActiveHybrid 5', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'ActiveHybrid 7', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'ActiveHybrid X6', category:'SUV', size:'L', },
    { make:'BMW', model: 'Alpina B6 xDrive Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'Alpina B7 xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'Alpina B7', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'i3', category:'SEDAN', size:'M', },
    { make:'BMW', model: 'i5', category:'SUV', size:'E', },
    { make:'BMW', model: 'i8', category:'EXOTIC', size:'E', },
    { make:'BMW', model: 'L6', category:'COUPE', size:'L', },
    { make:'BMW', model: 'L7', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'M Coupe', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M Roadster', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M235i', category:'COUPE', size:'M', },
    { make:'BMW', model: 'M235i xDrive', category:'COUPE', size:'M', },
    { make:'BMW', model: 'M240i', category:'COUPE', size:'M', },
    { make:'BMW', model: 'M3', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'M340i', category:'SEDAN', size:'M', },
    { make:'BMW', model: 'M4', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M5', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'M6', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M6 Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'X1', category:'SUV', size:'L', },
    { make:'BMW', model: 'X2', category:'SUV', size:'L', },
    { make:'BMW', model: 'X3', category:'SUV', size:'L', },
    { make:'BMW', model: 'X4', category:'SUV', size:'L', },
    { make:'BMW', model: 'X5', category:'SUV', size:'L', },
    { make:'BMW', model: 'X5 M', category:'SUV', size:'L', },
    { make:'BMW', model: 'X6', category:'SUV', size:'L', },
    { make:'BMW', model: 'X6 M', category:'SUV', size:'L', },
    { make:'BMW', model: 'X7', category:'SUV', size:'E', },
    { make:'BMW', model: 'Z3', category:'COUPE', size:'M', },
    { make:'BMW', model: 'Z3M', category:'COUPE', size:'L', },
    { make:'BMW', model: 'Z4', category:'COUPE', size:'M', },
    { make:'BMW', model: 'Z8', category:'EXOTIC', size:'E', },

  ]);
};
