
exports.seed = function(knex) {
  return knex('cars').insert([
    { make:'Acura', model: 'CL', category:'COUPE', size:'M', }, 
    { make:'Acura', model: 'ILX', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'Integra', category:'COUPE', size:'S', },
    { make:'Acura', model: 'Legend', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'MDX', category:'SUV', size:'L', }, 
    { make:'Acura', model: 'NSX', category:'EXOTIC', size:'E', },
    { make:'Acura', model: 'RDX', category:'SUV', size:'L', },
    { make:'Acura', model: 'RL', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'RLX', category:'SEDAN', size:'M', }, 
    { make:'Acura', model: 'RSX', category:'COUPE', size:'S', },
    { make:'Acura', model: 'SLX', category:'SUV', size:'L', },
    { make:'Acura', model: 'TL', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'TLX', category:'SEDAN', size:'M', }, 
    { make:'Acura', model: 'TSX', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'Vigor', category:'SEDAN', size:'M', },
    { make:'Acura', model: 'ZDX', category:'SUV', size:'L', },

    { make:'Alfa Romeo', model: '4C', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: '8C', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: '8C Competizione', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: 'C4', category:'EXOTIC', size:'E', },
    { make:'Alfa Romeo', model: 'Giulia', category:'SEDAN', size:'L', },
    { make:'Alfa Romeo', model: 'Giulietta', category:'COUPE', size:'M', },
    { make:'Alfa Romeo', model: 'Milano', category:'SEDAN', size:'M', },
    { make:'Alfa Romeo', model: 'Spider', category:'COUPE', size:'M', },
    { make:'Alfa Romeo', model: 'Stelvio', category:'SUV', size:'L', },

    { make:'Aston Martin', model: 'DB11', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DB7', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DB9', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DBS', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'DBS Superleggera', category:'COUPE', size:'E', },
    { make:'Aston Martin', model: 'DBX', category:'SUV', size:'E', },
    { make:'Aston Martin', model: 'Lagonda', category:'SEDAN', size:'L', },
    { make:'Aston Martin', model: 'One-77', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'Rapide', category:'SEDAN', size:'E', },
    { make:'Aston Martin', model: 'Valkyrie', category:'COUPE', size:'E', },
    { make:'Aston Martin', model: 'Vanquish', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'Vantage', category:'EXOTIC', size:'E', },
    { make:'Aston Martin', model: 'Virage', category:'EXOTIC', size:'E', },

    { make:'Audi', model: '100', category:'SEDAN', size:'M', },
    { make:'Audi', model: '4000', category:'SEDAN', size:'M', },
    { make:'Audi', model: '5000', category:'SEDAN', size:'M', },
    { make:'Audi', model: '80', category:'SEDAN', size:'M', },
    { make:'Audi', model: '90', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A3', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A4', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A5', category:'COUPE', size:'M', },
    { make:'Audi', model: 'A5 Sportback', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A6', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'A7', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'A8', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'Allroad', category:'SEDAN', size:'M', },
    { make:'Audi', model: 'Cabriolet', category:'COUPE', size:'M', },
    { make:'Audi', model: 'Coupe', category:'COUPE', size:'M', },
    { make:'Audi', model: 'E-Tron Quattro', category:'SUV', size:'E', },
    { make:'Audi', model: 'Q3', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q4', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q5', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q7', category:'SUV', size:'L', },
    { make:'Audi', model: 'Q8', category:'SUV', size:'E', },
    { make:'Audi', model: 'R8', category:'EXOTIC', size:'E', },
    { make:'Audi', model: 'RS 3', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'RS 4', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'RS 5', category:'COUPE', size:'L', },
    { make:'Audi', model: 'RS 6', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'RS 7', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S3', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S4', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S5', category:'COUPE', size:'L', },
    { make:'Audi', model: 'S6', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S7', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'S8', category:'SEDAN', size:'L', },
    { make:'Audi', model: 'SQ5', category:'SUV', size:'L', },
    { make:'Audi', model: 'TT', category:'COUPE', size:'M', },
    { make:'Audi', model: 'TT RS', category:'COUPE', size:'L', },
    { make:'Audi', model: 'TTS', category:'COUPE', size:'L', },
    { make:'Audi', model: 'V8 Quattro', category:'SEDAN', size:'M', },

    { make:'Bentley', model: 'Arnage', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Azure', category:'EXOTIC', size:'E', },
    { make:'Bentley', model: 'Bentayga', category:'SUV', size:'E', },
    { make:'Bentley', model: 'Brooklands', category:'EXOTIC', size:'E', },
    { make:'Bentley', model: 'Continental', category:'EXOTIC', size:'E', },
    { make:'Bentley', model: 'Continental GT', category:'E', size:'E', },
    { make:'Bentley', model: 'Eight', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Flying Spur', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Mulsanne', category:'SEDAN', size:'E', },
    { make:'Bentley', model: 'Turbo R', category:'SEDAN', size:'E', },

    { make:'BMW', model: '128i', category:'COUPE', size:'M', },
    { make:'BMW', model: '135i', category:'COUPE', size:'M', },
    { make:'BMW', model: '135iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '228i', category:'COUPE', size:'M', },
    { make:'BMW', model: '228i xDrive', category:'COUPE', size:'M', },
    { make:'BMW', model: '230i', category:'COUPE', size:'M', },
    { make:'BMW', model: '318i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '318iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '318ti', category:'COUPE', size:'M', },
    { make:'BMW', model: '320i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '320i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '323ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '323i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '323iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '325Ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '325e', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325eS', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325i', category:'COUPE', size:'M', },
    { make:'BMW', model: '325iS', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325iX', category:'SEDAN', size:'M', },
    { make:'BMW', model: '325xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328 Gran Tourismo xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328 xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328Ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '328d', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328d xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '328iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '328xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '330Ci', category:'COUPE', size:'M', },
    { make:'BMW', model: '330e', category:'SEDAN', size:'M', },
    { make:'BMW', model: '330i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '330xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335d', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335i Gran Tourismo xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '335iS', category:'COUPE', size:'M', },
    { make:'BMW', model: '335xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '340i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '428i', category:'COUPE', size:'M', },
    { make:'BMW', model: '428i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '428i Gran Coupe xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '428i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '430i', category:'COUPE', size:'M', },
    { make:'BMW', model: '430i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '435i', category:'COUPE', size:'M', },
    { make:'BMW', model: '435i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '435i Gran Coupe xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '435i xDrive', category:'COUPE', size:'M', },
    { make:'BMW', model: '440i', category:'COUPE', size:'M', },
    { make:'BMW', model: '440i Gran Coupe', category:'SEDAN', size:'M', },
    { make:'BMW', model: '525i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '525xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '528i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '530i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '530xi', category:'SEDAN', size:'M', },
    { make:'BMW', model: '533i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535d', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535d xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535i', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535i Gran Tourismo', category:'SEDAN', size:'M', },
    { make:'BMW', model: '535i Gran Tourismo xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '550i xDrive', category:'SEDAN', size:'M', },
    { make:'BMW', model: '633CSi', category:'COUPE', size:'L', },
    { make:'BMW', model: '635CSi', category:'COUPE', size:'M', },
    { make:'BMW', model: '640i', category:'COUPE', size:'L', },
    { make:'BMW', model: '640i Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: '640i xDrive', category:'COUPE', size:'L', },
    { make:'BMW', model: '645Ci', category:'COUPE', size:'L', },
    { make:'BMW', model: '650i', category:'COUPE', size:'L', },
    { make:'BMW', model: '650i Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: '650i Gran Coupe xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '650i xDrive', category:'COUPE', size:'L', },
    { make:'BMW', model: '733i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '735i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '735iL', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740iL', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740Ld xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '740Li xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '745i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '745Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750i xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750iL', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '750Li xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: '760i', category:'SEDAN', size:'L', },
    { make:'BMW', model: '760Li', category:'SEDAN', size:'L', },
    { make:'BMW', model: '840Ci', category:'COUPE', size:'L', },
    { make:'BMW', model: '850Ci', category:'COUPE', size:'L', },
    { make:'BMW', model: '850CSi', category:'COUPE', size:'L', },
    { make:'BMW', model: '850i', category:'COUPE', size:'L', },
    { make:'BMW', model: 'ActiveHybrid 3', category:'SEDAN', size:'M', },
    { make:'BMW', model: 'ActiveHybrid 4', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'ActiveHybrid 5', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'ActiveHybrid 7', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'ActiveHybrid X6', category:'SUV', size:'L', },
    { make:'BMW', model: 'Alpina B6 xDrive Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'Alpina B7 xDrive', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'Alpina B7', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'i3', category:'SEDAN', size:'M', },
    { make:'BMW', model: 'i5', category:'SUV', size:'E', },
    { make:'BMW', model: 'i8', category:'EXOTIC', size:'E', },
    { make:'BMW', model: 'L6', category:'COUPE', size:'L', },
    { make:'BMW', model: 'L7', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'M Coupe', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M Roadster', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M235i', category:'COUPE', size:'M', },
    { make:'BMW', model: 'M235i xDrive', category:'COUPE', size:'M', },
    { make:'BMW', model: 'M240i', category:'COUPE', size:'M', },
    { make:'BMW', model: 'M3', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'M340i', category:'SEDAN', size:'M', },
    { make:'BMW', model: 'M4', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M5', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'M6', category:'COUPE', size:'L', },
    { make:'BMW', model: 'M6 Gran Coupe', category:'SEDAN', size:'L', },
    { make:'BMW', model: 'X1', category:'SUV', size:'L', },
    { make:'BMW', model: 'X2', category:'SUV', size:'L', },
    { make:'BMW', model: 'X3', category:'SUV', size:'L', },
    { make:'BMW', model: 'X4', category:'SUV', size:'L', },
    { make:'BMW', model: 'X5', category:'SUV', size:'L', },
    { make:'BMW', model: 'X5 M', category:'SUV', size:'L', },
    { make:'BMW', model: 'X6', category:'SUV', size:'L', },
    { make:'BMW', model: 'X6 M', category:'SUV', size:'L', },
    { make:'BMW', model: 'X7', category:'SUV', size:'E', },
    { make:'BMW', model: 'Z3', category:'COUPE', size:'M', },
    { make:'BMW', model: 'Z3M', category:'COUPE', size:'L', },
    { make:'BMW', model: 'Z4', category:'COUPE', size:'M', },
    { make:'BMW', model: 'Z8', category:'EXOTIC', size:'E', },

    { make:'Bugatti', model: 'Chiron', category:'EXOTIC', size:'E', },
    { make:'Bugatti', model: 'Grand Sport', category:'EXOTIC', size:'E', },
    { make:'Bugatti', model: 'Veyron', category:'EXOTIC', size:'E', },

    { make:'Buick', model: 'Cascada', category:'COUPE', size:'M', },
    { make:'Buick', model: 'Century', category:'SEDAN', size:'M', },
    { make:'Buick', model: 'Enclave', category:'SUV', size:'L', },
    { make:'Buick', model: 'Encore', category:'SUV', size:'L', },
    { make:'Buick', model: 'Envision', category:'SUV', size:'L', },
    { make:'Buick', model: 'LaCrosse', category:'SEDAN', size:'M', },
    { make:'Buick', model: 'Le Sabre', category:'SEDAN', size:'M', },
    { make:'Buick', model: 'Lucerne', category:'SEDAN', size:'M', },
    { make:'Buick', model: 'Park Avenue', category:'SEDAN', size:'S', },
    { make:'Buick', model: 'Rainier', category:'SUV', size:'L', },
    { make:'Buick', model: 'Reatta', category:'COUPE', size:'S', },
    { make:'Buick', model: 'Regal', category:'SEDAN', size:'M', },
    { make:'Buick', model: 'Rendezvous', category:'SUV', size:'L', },
    { make:'Buick', model: 'Skyhawk', category:'SEDAN', size:'S', },
    { make:'Buick', model: 'Skylark', category:'COUPE', size:'M', },
    { make:'Buick', model: 'Somerset', category:'COUPE', size:'S', },
    { make:'Buick', model: 'Terraza', category:'MINIVAN', size:'L', },
    { make:'Buick', model: 'Verano', category:'SEDAN', size:'S', },

    { make:'Cadillac', model: 'Allante', category:'COUPE', size:'M', },
    { make:'Cadillac', model: 'ATS', category:'SEDAN', size:'M', },
    { make:'Cadillac', model: 'ATS-V', category:'SEDAN', size:'M', },
    { make:'Cadillac', model: 'Catera', category:'SEDAN', size:'M', },
    { make:'Cadillac', model: 'CT-6', category:'SEDAN', size:'L', },
    { make:'Cadillac', model: 'CTS', category:'SEDAN', size:'M', },
    { make:'Cadillac', model: 'CTS-V', category:'SEDAN', size:'M', },
    { make:'Cadillac', model: 'DTS', category:'SEDAN', size:'M', },
    { make:'Cadillac', model: 'El Dorado', category:'COUPE', size:'L', },
    { make:'Cadillac', model: 'ELR', category:'COUPE', size:'M', },
    { make:'Cadillac', model: 'Escalade', category:'SUV', size:'E', },
    { make:'Cadillac', model: 'Escalade ESV', category:'SUV', size:'E', },
    { make:'Cadillac', model: 'Escalade EXT', category:'TRUCK', size:'E', },
    { make:'Cadillac', model: 'SRX', category:'SUV', size:'L', },
    { make:'Cadillac', model: 'STS', category:'SEDAN', size:'M', },
    { make:'Cadillac', model: 'XLR', category:'COUPE', size:'E', },
    { make:'Cadillac', model: 'XT5', category:'SUV', size:'L', },
    { make:'Cadillac', model: 'XT6', category:'SUV', size:'L', },
    { make:'Cadillac', model: 'XTS', category:'SEDAN', size:'L', },

    { make:'Chevrolet', model: 'Astro', category:'MINIVAN', size:'L', },
    { make:'Chevrolet', model: 'Avalanche', category:'TRUCK', size:'E', },
    { make:'Chevrolet', model: 'Aveo', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Aveo5', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Beretta', category:'COUPE', size:'M', },
    { make:'Chevrolet', model: 'Blazer', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'Bolt', category:'SEDAN', size:'M', },
    { make:'Chevrolet', model: 'Camaro', category:'COUPE', size:'M', },
    { make:'Chevrolet', model: 'Captiva Sport', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'Cavalier', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'City Express', category:'MINIVAN', size:'L', },
    { make:'Chevrolet', model: 'Cobalt', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Colorado', category:'TRUCK', size:'L', },
    { make:'Chevrolet', model: 'Corsica', category:'SEDAN', size:'M', },
    { make:'Chevrolet', model: 'Corvette', category:'COUPE', size:'L', },
    { make:'Chevrolet', model: 'Cruze', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'El Camino', category:'TRUCK', size:'L', },
    { make:'Chevrolet', model: 'Equinox', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'Express 1500', category:'VAN', size:'E', },
    { make:'Chevrolet', model: 'Express 2500', category:'VAN', size:'E', },
    { make:'Chevrolet', model: 'Express 3500', category:'VAN', size:'E', },
    { make:'Chevrolet', model: 'HHR', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Impala', category:'SEDAN', size:'M', },
    { make:'Chevrolet', model: 'Lumina', category:'SEDAN', size:'M', },
    { make:'Chevrolet', model: 'LUV', category:'TRUCK', size:'S', },
    { make:'Chevrolet', model: 'Malibu', category:'SEDAN', size:'M', },
    { make:'Chevrolet', model: 'Metro', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Monte Carlo', category:'COUPE', size:'M', },
    { make:'Chevrolet', model: 'Prizm', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'S10 Blazer', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'S10 Pickup', category:'TRUCK', size:'L', },
    { make:'Chevrolet', model: 'Silverado 1500', category:'TRUCK', size:'L', },
    { make:'Chevrolet', model: 'Silverado 2500', category:'TRUCK', size:'E', },
    { make:'Chevrolet', model: 'Silverado 3500', category:'TRUCK', size:'E', },
    { make:'Chevrolet', model: 'Sonic', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Spark', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Spectrum', category:'SEDAN', size:'S', },
    { make:'Chevrolet', model: 'Sprint', category:'COUPE', size:'S', },
    { make:'Chevrolet', model: 'SS', category:'SEDAN', size:'L', },
    { make:'Chevrolet', model: 'SSR', category:'TRUCK', size:'E', },
    { make:'Chevrolet', model: 'Suburban', category:'SUV', size:'E', },
    { make:'Chevrolet', model: 'Tahoe', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'Tracker', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'TrailBlazer', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'TrailBlazer EXT', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'Traverse', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'Trax', category:'SUV', size:'L', },
    { make:'Chevrolet', model: 'Uplander', category:'MINIVAN', size:'L', },
    { make:'Chevrolet', model: 'Venture', category:'MINIVAN', size:'L', },
    { make:'Chevrolet', model: 'Volt', category:'SEDAN', size:'M', },

    { make:'Chrysler', model: '200', category:'SEDAN', size:'S', },
    { make:'Chrysler', model: '300', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: '300M', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: 'Aspen', category:'SUV', size:'L', },
    { make:'Chrysler', model: 'Cirrus', category:'SEDAN', size:'S', },
    { make:'Chrysler', model: 'Concorde', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: 'Cordoba', category:'COUPE', size:'M', },
    { make:'Chrysler', model: 'Crossfire', category:'COUPE', size:'M', },
    { make:'Chrysler', model: 'E Class', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: 'Fifth Avenue', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: 'Grand Voyager', category:'MINVAN', size:'L', },
    { make:'Chrysler', model: 'Laser', category:'COUPE', size:'M', },
    { make:'Chrysler', model: 'LeBaron', category:'COUPE', size:'M', },
    { make:'Chrysler', model: 'LeBaron GTS', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: 'LHS', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: 'New Yorker', category:'SEDAN', size:'M', },
    { make:'Chrysler', model: 'Pacifica', category:'SUV', size:'L', },
    { make:'Chrysler', model: 'Prowler', category:'EXOTIC', size:'E', },
    { make:'Chrysler', model: 'PT Cruiser', category:'SEDAN', size:'S', },
    { make:'Chrysler', model: 'Sebring', category:'SEDAN', size:'S', },
    { make:'Chrysler', model: 'Town & Country', category:'MINIVAN', size:'L', },
    { make:'Chrysler', model: 'Voyager', category:'MINIVAN', size:'L', },

    { make:'Daewoo', model: 'Lanos', category:'SEDAN', size:'S', },
    { make:'Daewoo', model: 'Leganza', category:'SEDAN', size:'S', },
    { make:'Daewoo', model: 'Nubira', category:'SEDAN', size:'S', },

    { make:'Dodge', model: 'Avenger', category:'SEDAN', size:'S', },
    { make:'Dodge', model: 'B1500', category:'VAN', size:'E', },
    { make:'Dodge', model: 'B250', category:'VAN', size:'E', },
    { make:'Dodge', model: 'B2500', category:'VAN', size:'E', },
    { make:'Dodge', model: 'Caliber', category:'SUV', size:'L', },
    { make:'Dodge', model: 'Caravan', category:'MINIVAN', size:'L', },
    { make:'Dodge', model: 'Challenger', category:'COUPE', size:'M', },
    { make:'Dodge', model: 'Charger', category:'SEDAN', size:'M', },
    { make:'Dodge', model: 'Dakota', category:'TRUCK', size:'L', },
    { make:'Dodge', model: 'Dart', category:'SEDAN', size:'S', },
    { make:'Dodge', model: 'Durango', category:'SUV', size:'L', },
    { make:'Dodge', model: 'Grand Caravan', category:'MINIVAN', size:'L', },
    { make:'Dodge', model: 'Intrepid', category:'SEDAN', size:'S', },
    { make:'Dodge', model: 'Journey', category:'SUV', size:'L', },
    { make:'Dodge', model: 'Magnum', category:'SEDAN', size:'S', },
    { make:'Dodge', model: 'Mini Ram Van', category:'MINIVAN', size:'L', },
    { make:'Dodge', model: 'Neon', category:'SEDAN', size:'S', },
    { make:'Dodge', model: 'Nitro', category:'SUV', size:'L', },
    { make:'Dodge', model: 'Ram 1500', category:'TRUCK', size:'L', },
    { make:'Dodge', model: 'Ram 2500', category:'TRUCK', size:'E', },
    { make:'Dodge', model: 'Ram 3500', category:'TRUCK', size:'E', },
    { make:'Dodge', model: 'Ram Promaster City', category:'MINIVAN', size:'E', },
    { make:'Dodge', model: 'Ram SRT-10', category:'TRUCK', size:'E', },
    { make:'Dodge', model: 'SRT-4', category:'SEDAN', size:'S', },
    { make:'Dodge', model: 'Stratus', category:'SEDAN', size:'S', },
    { make:'Dodge', model: 'Viper', category:'EXOTIC', size:'E', },

    { make:'Factory Five', model: '818', category:'EXOTIC', size:'E', },
    { make:'Factory Five', model: 'GTM', category:'EXOTIC', size:'E', },
    { make:'Factory Five', model: 'Hot Rod', category:'EXOTIC', size:'E', },
    { make:'Factory Five', model: 'MK2', category:'EXOTIC', size:'E', },
    { make:'Factory Five', model: 'MK3', category:'EXOTIC', size:'E', },
    { make:'Factory Five', model: 'MK4', category:'EXOTIC', size:'E', },
    { make:'Factory Five', model: 'Type 65', category:'EXOTIC', size:'E', },

    { make:'Ferrari', model: '308', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '328', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '348', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '360', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '360-Replica', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '456 GT', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '456M GT', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '458 Italia', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '488 Spider', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '512M', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '512TR', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '550 Maranello', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '575M Maranello', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '599 GTB Fiorano', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '599 GTO', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '612 Scaglietti', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '750 Monza', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: '812 Superfast', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'California', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'Enzo', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'F12 Berlinetta', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'F355', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'F355-Replica', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'F40', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'F50', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'F50-Replica', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'FF', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'FXX', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'GTC4 Luso', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'GTO', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'LaFerrari', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'Mondial', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'Testarossa', category:'EXOTIC', size:'E', },
    { make:'Ferrari', model: 'Testarossa-Replica', category:'EXOTIC', size:'E', },

    { make:'Fiat', model: '124 Spider', category:'COUPE', size:'M', },
    { make:'Fiat', model: '500', category:'COUPE', size:'S', },
    { make:'Fiat', model: '500L', category:'SEDAN', size:'S', },
    { make:'Fiat', model: '500X', category:'SEDAN', size:'S', },
    { make:'Fiat', model: 'Strada', category:'TRUCK', size:'L', },

    { make:'Fisker', model: 'Karma', category:'SEDAN', size:'L', },
    
    { make:'Ford', model: 'Aerostar', category:'MINIVAN', size:'L', },
    { make:'Ford', model: 'Aspire', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Bronco', category:'SUV', size:'L', },
    { make:'Ford', model: 'Bronco II', category:'SUV', size:'L', },
    { make:'Ford', model: 'C-MAX', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'Contour', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Courier', category:'TRUCK', size:'S', },
    { make:'Ford', model: 'Crown Victoria', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'E-150', category:'VAN', size:'E', },
    { make:'Ford', model: 'E-250', category:'VAN', size:'E', },
    { make:'Ford', model: 'E-350', category:'VAN', size:'E', },
    { make:'Ford', model: 'Ecosport', category:'SUV', size:'M', },
    { make:'Ford', model: 'Edge', category:'SUV', size:'L', },
    { make:'Ford', model: 'Escape', category:'SUV', size:'L', },
    { make:'Ford', model: 'Escort', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Excursion', category:'SUV', size:'E', },
    { make:'Ford', model: 'EXP', category:'COUPE', size:'S', },
    { make:'Ford', model: 'Expedition', category:'SUV', size:'E', },
    { make:'Ford', model: 'Expedition EL', category:'SUV', size:'E', },
    { make:'Ford', model: 'Explorer', category:'SUV', size:'L', },
    { make:'Ford', model: 'Explorer Sport Trac', category:'TRUCK', size:'L', },
    { make:'Ford', model: 'F-150', category:'TRUCK', size:'L', },
    { make:'Ford', model: 'F-250', category:'TRUCK', size:'E', },
    { make:'Ford', model: 'F-350', category:'TRUCK', size:'E', },
    { make:'Ford', model: 'Festiva', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Fiesta', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Five Hundred', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'Flex', category:'SUV', size:'L', },
    { make:'Ford', model: 'Focus', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Freestyle', category:'MINIVAN', size:'L', },
    { make:'Ford', model: 'Fusion', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'GT', category:'EXOTIC', size:'E', },
    { make:'Ford', model: 'GT40-Replica', category:'EXOTIC', size:'E', },
    { make:'Ford', model: 'Mustang', category:'COUPE', size:'M', },
    { make:'Ford', model: 'Ranger', category:'TRUCK', size:'L', },
    { make:'Ford', model: 'Raptor', category:'TRUCK', size:'E', },
    { make:'Ford', model: 'Taurus', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'Taurus X', category:'SUV', size:'L', },
    { make:'Ford', model: 'Thunderbird', category:'COUPE', size:'M', },
    { make:'Ford', model: 'Transit Connect', category:'MINIVAN', size:'E', },
    { make:'Ford', model: 'Windstar', category:'MINIVAN', size:'L', },
    { make:'Ford', model: 'ZX2 Escort', category:'COUPE', size:'S', },
    
    { make:'Genesis', model: 'G70', category:'SEDAN', size:'L', },
    { make:'Genesis', model: 'G80', category:'SEDAN', size:'L', },
    { make:'Genesis', model: 'G90', category:'SEDAN', size:'L', },

    { make:'Geo', model: 'Metro', category:'SEDAN', size:'S', },
    { make:'Geo', model: 'Prism', category:'SEDAN', size:'S', },
    { make:'Geo', model: 'Spectrum', category:'SEDAN', size:'S', },
    { make:'Geo', model: 'Storm', category:'COUPE', size:'S', },
    { make:'Geo', model: 'Tracker', category:'SUV', size:'L', },

    { make:'GMC', model: 'Acadia', category:'SUV', size:'L', },
    { make:'GMC', model: 'Canyon', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Envoy', category:'SUV', size:'L', },
    { make:'GMC', model: 'Envoy XL', category:'SUV', size:'L', },
    { make:'GMC', model: 'Envoy XUV', category:'SUV', size:'L', },
    { make:'GMC', model: 'G1500', category:'VAN', size:'E', },
    { make:'GMC', model: 'G2500', category:'VAN', size:'E', },
    { make:'GMC', model: 'G3500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Jimmy', category:'SUV', size:'L', },
    { make:'GMC', model: 'S15 Jimmy', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'S15 Pickup', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Safari', category:'MINIVAN', size:'L', },
    { make:'GMC', model: 'Savana 1500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Savana 2500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Savana 3500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Sierra 1500', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Sierra 2500', category:'TRUCK', size:'E', },
    { make:'GMC', model: 'Sierra 3500', category:'TRUCK', size:'E', },
    { make:'GMC', model: 'Sonoma', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Suburban', category:'SUV', size:'E', },
    { make:'GMC', model: 'Syclone', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Terrain', category:'SUV', size:'L', },
    { make:'GMC', model: 'Typhoon', category:'SUV', size:'L', },
    { make:'GMC', model: 'Yukon', category:'SUV', size:'L', },
    { make:'GMC', model: 'Yukon XL', category:'SUV', size:'E', },

    { make:'Honda', model: 'Accord', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'Accord Crosstour', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'Civic', category:'SEDAN', size:'S', },
    { make:'Honda', model: 'Clarity', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'CR-V', category:'SUV', size:'L', },
    { make:'Honda', model: 'CR-Z', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Crosstour', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'CRX', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Del Sol', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Element', category:'SUV', size:'L', },
    { make:'Honda', model: 'Fit', category:'SEDAN', size:'S', },
    { make:'Honda', model: 'HR-V', category:'SUV', size:'L', },
    { make:'Honda', model: 'Insight', category:'SEDAN', size:'S', },
    { make:'Honda', model: 'Odyssey', category:'MINIVAN', size:'L', },
    { make:'Honda', model: 'Passport', category:'SUV', size:'L', },
    { make:'Honda', model: 'Pilot', category:'SUV', size:'L', },
    { make:'Honda', model: 'Prelude', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Ridgeline', category:'TRUCK', size:'L', },
    { make:'Honda', model: 'S2000', category:'COUPE', size:'M', },

    { make:'Hummer', model: 'H1', category:'SUV', size:'E', },
    { make:'Hummer', model: 'H2', category:'SUV', size:'E', },
    { make:'Hummer', model: 'H3', category:'SUV', size:'L', },
    { make:'Hummer', model: 'H3T', category:'TRUCK', size:'L', },

    { make:'Hyundai', model: 'Accent', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Azera', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Elantra', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Elantra Coupe', category:'COUPE', size:'S', },
    { make:'Hyundai', model: 'Elantra GT', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Elantra Touring', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Entourage', category:'MINIVAN', size:'L', },
    { make:'Hyundai', model: 'Equus', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Excel', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Genesis', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Genesis Coupe', category:'COUPE', size:'M', },
    { make:'Hyundai', model: 'Ioniq', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Kona', category:'SUV', size:'M', },
    { make:'Hyundai', model: 'Nexo', category:'SUV', size:'M', },
    { make:'Hyundai', model: 'Palisade', category:'SUV', size:'E', },
    { make:'Hyundai', model: 'Santa Fe', category:'SUV', size:'L', },
    { make:'Hyundai', model: 'S Coupe', category:'COUPE', size:'S', },
    { make:'Hyundai', model: 'Sonata', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Tiburon', category:'COUPE', size:'S', },
    { make:'Hyundai', model: 'Tucson', category:'SUV', size:'L', },
    { make:'Hyundai', model: 'Veloster', category:'COUPE', size:'M', },
    { make:'Hyundai', model: 'Veracruz', category:'SUV', size:'L', },
    { make:'Hyundai', model: 'XG300', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'XG350', category:'SEDAN', size:'M', },

    { make:'Infiniti', model: 'EX35', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'EX37', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX35', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX37', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX45', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX50', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'G20', category:'SEDAN', size:'S', },
    { make:'Infiniti', model: 'G25', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'G35', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'G37', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'I30', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'I35', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'J30', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'JX35', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'M30', category:'COUPE', size:'M', },
    { make:'Infiniti', model: 'M35', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'M35h', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'M37', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'M45', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'M56', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'Q40', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q45', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q50', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q60', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q70', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'QX30', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX4', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX50', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX56', category:'SUV', size:'E', },
    { make:'Infiniti', model: 'QX60', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX70', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX80', category:'SUV', size:'E', },

    { make:'Isuzu', model: 'Amigo', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Ascender', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Axiom', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Hombre', category:'TRUCK', size:'L', },
    { make:'Isuzu', model: 'I-Mark', category:'COUPE', size:'M', },
    { make:'Isuzu', model: 'Impulse', category:'COUPE', size:'S', },
    { make:'Isuzu', model: 'Oasis', category:'MINIVAN', size:'L', },
    { make:'Isuzu', model: 'Rodeo', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Stylus', category:'SEDAN', size:'S', },
    { make:'Isuzu', model: 'Trooper', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Trooper II', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'VehiCROSS', category:'SUV', size:'L', },

    { make:'Jaguar', model: 'E-Pace', category:'SUV', size:'L', },
    { make:'Jaguar', model: 'F-Pace', category:'SUV', size:'L', },
    { make:'Jaguar', model: 'F-Type', category:'COUPE', size:'M', },
    { make:'Jaguar', model: 'I-Pace', category:'SUV', size:'L', },
    { make:'Jaguar', model: 'S-Type', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'X-Type', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XE', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XF', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XF SportBrake', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XJ', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ Sport', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ Vanden Plus', category:'', size:'L', },
    { make:'Jaguar', model: 'XJ12', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ6', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ8', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ8 L', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJR', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJR-S', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XJS', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XK', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XK8', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XKR', category:'COUPE', size:'L', },

    { make:'Jeep', model: 'Cherokee', category:'SUV', size:'L', },
    { make:'Jeep', model: 'CJ', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Comanche', category:'TRUCK', size:'L', },
    { make:'Jeep', model: 'Commander', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Compass', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Gladiator', category:'TRUCK', size:'E', },
    { make:'Jeep', model: 'Grand Cherokee', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Grand Wagoneer', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Liberty', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Patriot', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Pickup', category:'TRUCK', size:'L', },
    { make:'Jeep', model: 'Renegade', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Scrambler', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Wagoneer', category:'SUV', size:'E', },
    { make:'Jeep', model: 'Wrangler', category:'SUV', size:'L', },

    { make:'Kia', model: 'Amanti', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Borrego', category:'SUV', size:'L', },
    { make:'Kia', model: 'Cadenza', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Forte', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Forte Koup', category:'COUPE', size:'S', },
    { make:'Kia', model: 'K900', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Niro', category:'SUV', size:'L', },
    { make:'Kia', model: 'Optima', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Rio', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Rio5', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Rondo', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Sedona', category:'MINIVAN', size:'L', },
    { make:'Kia', model: 'Sephia', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Sorento', category:'SUV', size:'L', },
    { make:'Kia', model: 'Soul', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Spectra', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Spectra5', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Sportage', category:'SUV', size:'L', },
    { make:'Kia', model: 'Stinger', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Telluride', category:'SUV', size:'E', },

    { make:'Koenigsegg', model: 'CCR', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'CCS8', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'CCX', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'CCXR', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'Regera', category:'EXOTIC', size:'E', },

    { make:'Lamborghini', model: 'Aventador', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Countach', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Countach-Replica', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Diablo', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Diablo-Replica', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Gallardo', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Huracan', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Jalpa', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'LM002', category:'SUV', size:'E', },
    { make:'Lamborghini', model: 'Murcielago', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Murcielago-Replica', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Urus', category:'SUV', size:'E', },

    { make:'Land Rover', model: 'Defender', category:'SUV', size:'E', },
    { make:'Land Rover', model: 'Discovery', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Discovery Sport', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Freelander', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'LR2', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'LR3', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'LR4', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Range Rover', category:'SUV', size:'E', },
    { make:'Land Rover', model: 'Range Rover Evoque', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Range Rover Sport', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Range Rover Velar', category:'SUV', size:'E', },

    { make:'Lexus', model: 'CT 200h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 250', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 300', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 300h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 330', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 350', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 200t', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 300', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 350', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 400', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 430', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 450h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 460', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GX 460', category:'SUV', size:'L', },
    { make:'Lexus', model: 'GX 470', category:'SUV', size:'L', },
    { make:'Lexus', model: 'HS 250h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 200t', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 250', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 250c', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'IS 300', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 350', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 350c', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'IS F', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LC 500', category:'COUPE', size:'E', },
    { make:'Lexus', model: 'LFA', category:'EXOTIC', size:'E', },
    { make:'Lexus', model: 'LS', category:'SUV', size:'E', },
    { make:'Lexus', model: 'LS 400', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LS 430', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LS 460', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LS 500', category:'SEDAN', size:'E', },
    { make:'Lexus', model: 'LS 600h', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LX 450', category:'SUV', size:'E', },
    { make:'Lexus', model: 'LX 470', category:'SUV', size:'E', },
    { make:'Lexus', model: 'LX 570', category:'SUV', size:'E', },
    { make:'Lexus', model: 'NX 200t', category:'SUV', size:'L', },
    { make:'Lexus', model: 'NX 300h', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RC 350', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'RC F', category:'COUPE', size:'L', },
    { make:'Lexus', model: 'RX 300', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 330', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 350', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 350L', category:'SUV', size:'E', },
    { make:'Lexus', model: 'RX 400h', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 450h', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 450HL', category:'SUV', size:'E', },
    { make:'Lexus', model: 'SC 300', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'SC 400', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'SC 430', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'UX', category:'SUV', size:'L', },

    { make:'Lincoln', model: 'Aviator', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'Blackwood', category:'TRUCK', size:'L', },
    { make:'Lincoln', model: 'Continental', category:'SEDAN', size:'L', },
    { make:'Lincoln', model: 'LS', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'Mark LT', category:'TRUCK', size:'L', },
    { make:'Lincoln', model: 'MKC', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'MKS', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'MKT', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'MKX', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'MKZ', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'Nautilus', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'Navigator', category:'SUV', size:'E', },
    { make:'Lincoln', model: 'Navigator L', category:'SUV', size:'E', },
    { make:'Lincoln', model: 'Town Car', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'Zephyr', category:'SEDAN', size:'M', },

    { make:'Lotus', model: 'Elise', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Elite', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Espirit', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Evora', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Exige', category:'EXOTIC', size:'E', },

    { make:'Maserati', model: '430', category:'SEDAN', size:'L', },
    { make:'Maserati', model: 'BiTurbo', category:'EXOTIC', size:'E', },
    { make:'Maserati', model: 'Ghibli', category:'SEDAN', size:'L', },
    { make:'Maserati', model: 'GranSport', category:'EXOTIC', size:'E', },
    { make:'Maserati', model: 'GranTourismo', category:'EXOTIC', size:'E', },
    { make:'Maserati', model: 'Levante', category:'SUV', size:'E', },
    { make:'Maserati', model: 'Quattroporte', category:'SEDAN', size:'L', },
    { make:'Maserati', model: 'Spyder', category:'EXOTIC', size:'E', },

    { make:'Maybach', model: '57', category:'SEDAN', size:'E', },
    { make:'Maybach', model: '62', category:'SEDAN', size:'E', },
    { make:'Maybach', model: '62S Landaulet', category:'SEDAN', size:'E', },

    { make:'Mazda', model: '323', category:'SEDAN', size:'S', },
    { make:'Mazda', model: '626', category:'SEDAN', size:'M', },
    { make:'Mazda', model: '929', category:'SEDAN', size:'M', },
    { make:'Mazda', model: 'B-Series Pickup', category:'TRUCK', size:'L', },
    { make:'Mazda', model: 'CX-3', category:'SUV', size:'L', },
    { make:'Mazda', model: 'CX-5', category:'SUV', size:'L', },
    { make:'Mazda', model: 'CX-7', category:'SUV', size:'L', },
    { make:'Mazda', model: 'CX-9', category:'SUV', size:'L', },
    { make:'Mazda', model: 'Mazda2', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Mazda3', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Mazda5', category:'MINIVAN', size:'L', },
    { make:'Mazda', model: 'Mazda6', category:'SEDAN', size:'M', },
    { make:'Mazda', model: 'Mazdaspeed3', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Mazdaspeed6', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Millenia', category:'SEDAN', size:'M', },
    { make:'Mazda', model: 'MPV', category:'MINIVAN', size:'L', },
    { make:'Mazda', model: 'MX-5 Miata', category:'COUPE', size:'M', },
    { make:'Mazda', model: 'MX3', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'MX6', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'Protege', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Protege5', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'RX-7', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'RX-8', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'Tribute', category:'SUV', size:'L', },

    { make:'McLaren', model: '570S', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: '650S', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: '675LT', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: '720S', category:'COUPE', size:'E', },
    { make:'McLaren', model: 'F1', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: 'Hypercar', category:'COUPE', size:'E', },
    { make:'McLaren', model: 'MP4-12C', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: 'P1', category:'EXOTIC', size:'E', },

    { make:'Mercedes-Benz', model: '400SEL', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: '500SL', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: '600SL', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'A220', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'AMG GT', category:'EXOTIC', size:'E', },
    { make:'Mercedes-Benz', model: 'B-Class Electric Drive', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'C220', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C230', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C240', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C250', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C280', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C300', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C32 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C320', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C350', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C36 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C400', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C43 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C450', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C55 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C63 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CL500', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL550', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL600', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL500', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL550', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL600', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL65 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CLA250', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'CLA45 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLK320', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK350', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK430', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK500', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CLK550', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS400', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS450', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS500', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS63 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'E250', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E300', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E320', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E350', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E400', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E43 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'E450', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E500', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E55 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'E550', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E63 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'EQC400', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'G500', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'G55 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'G550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'G63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL320', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL350', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL450', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLA250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLA45 AMG', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLC300', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLC350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLC43 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLC63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLE300d', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE400', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE43 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLE450', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE550e', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLE63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLK250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLK350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLS350d', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 450', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 580', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLK250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLK350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLS 350d', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 450', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 580', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'Maybach S600', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'Metris', category:'VAN', size:'L', },
    { make:'Mercedes-Benz', model: 'ML250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML320', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML400', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML430', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML450', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML500', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML55 AMG', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML550', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'R320', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'R350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'R500', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'R63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'S320', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S350', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S400', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S420', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S430', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S450', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S500', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S55 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S550', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S560', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S600', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S63 AMG', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S65 AMG', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'SL20', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL400', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL550', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL600', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL65 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLC43 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLK230', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK250', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK280', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK300', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK32 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLK320', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK350', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLR', category:'EXOTIC', size:'E', },
    { make:'Mercedes-Benz', model: 'SLS AMG', category:'EXOTIC', size:'E', },

    { make:'Mercury', model: 'Grand Marquis', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Mariner', category:'SEDAN', size:'L', },
    { make:'Mercury', model: 'Maurader', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Montego', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Mountaineer', category:'SEDAN', size:'L', },
    { make:'Mercury', model: 'Mystique', category:'SEDAN', size:'S', },
    { make:'Mercury', model: 'Sable', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Tracer', category:'SEDAN', size:'S', },
    { make:'Mercury', model: 'Villager', category:'SEDAN', size:'L', },
    { make:'Mercury', model: 'Voyager', category:'SEDAN', size:'L', },

    { make:'MINI', model: 'Cooper', category:'COUPE', size:'M', },
    { make:'MINI', model: 'Cooper Clubman', category:'SEDAN', size:'M', },
    { make:'MINI', model: 'Cooper Countryman', category:'SEDAN', size:'M', },
    { make:'MINI', model: 'Cooper Coupe', category:'COUPE', size:'M', },
    { make:'MINI', model: 'Cooper Cooper Paceman', category:'COUPE', size:'M', },
    { make:'MINI', model: 'Cooper Cooper Roadster', category:'COUPE', size:'M', },

    { make:'Mitsubishi', model: '300GT', category:'COUPE', size:'M', },
    { make:'Mitsubishi', model: 'Diamante', category:'SEDAN', size:'M', },
    { make:'Mitsubishi', model: 'Eclipse', category:'COUPE', size:'S', },
    { make:'Mitsubishi', model: 'Eclipse Cross', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Endeavor', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Expo', category:'MINIVAN', size:'L', },
    { make:'Mitsubishi', model: 'Galant', category:'SEDAN', size:'M', },
    { make:'Mitsubishi', model: 'i', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'i-MiEV', category:'SEDAN', size:'M', },
    { make:'Mitsubishi', model: 'Lancer', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'Lancer Evolution', category:'SEDAN', size:'L', },
    { make:'Mitsubishi', model: 'Mighty Max', category:'TRUCK', size:'L', },
    { make:'Mitsubishi', model: 'Mirage', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'Montero', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Montero Sport', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Outlander', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Precis', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'Raider', category:'TRUCK', size:'L', },
    { make:'Mitsubishi', model: 'Starion', category:'COUPE', size:'S', },

    { make:'Morgan', model: 'Aero 8', category:'EXOTIC', size:'E', },
    { make:'Morgan', model: 'Super Sports', category:'EXOTIC', size:'E', },

    { make:'Mosler', model: 'MT900', category:'EXOTIC', size:'E', },
    
    { make:'Nissan', model: '200SX', category:'COUPE', size:'S', },
    { make:'Nissan', model: '240SX', category:'COUPE', size:'S', },
    { make:'Nissan', model: '300ZX', category:'COUPE', size:'M', },
    { make:'Nissan', model: '350Z', category:'COUPE', size:'M', },
    { make:'Nissan', model: '370Z', category:'COUPE', size:'M', },
    { make:'Nissan', model: 'Altima', category:'SEDAN', size:'M', },
    { make:'Nissan', model: 'Armada', category:'SUV', size:'E', },
    { make:'Nissan', model: 'Axxess', category:'MINIVAN', size:'L', },
    { make:'Nissan', model: 'Cube', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Frontier', category:'TRUCK', size:'L', },
    { make:'Nissan', model: 'GT-R', category:'EXOTIC', size:'E', },
    { make:'Nissan', model: 'Juke', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Kicks', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Leaf', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Maxima', category:'SEDAN', size:'M', },
    { make:'Nissan', model: 'Murano', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Murano CrossCabirolet', category:'SUV', size:'L', },
    { make:'Nissan', model: 'NV200', category:'MINIVAN', size:'E', },
    { make:'Nissan', model: 'Pathfinder', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Quest', category:'MINIVAN', size:'L', },
    { make:'Nissan', model: 'Rogue', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Sentra', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Titan', category:'TRUCK', size:'E', },
    { make:'Nissan', model: 'Versa', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Versa Note', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Xterra', category:'SUV', size:'L', },

    { make:'Noble', model: 'M10', category:'EXOTIC', size:'E', },
    { make:'Noble', model: 'M12', category:'EXOTIC', size:'E', },
    { make:'Noble', model: 'M400', category:'EXOTIC', size:'E', },

    { make:'Oldsmobile', model: 'Achieva', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Alero', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Aurora', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Bravada', category:'SEDAN', size:'L', },
    { make:'Oldsmobile', model: 'Cutlass', category:'SEDAN', size:'M', },
    { make:'Oldsmobile', model: 'Cutlass Supreme', category:'SEDAN', size:'M', },
    { make:'Oldsmobile', model: 'Intrigue', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Silhouette', category:'MINIVAN', size:'L', },

    { make:'Plymouth', model: 'Breeze', category:'SEDAN', size:'S', },
    { make:'Plymouth', model: 'Gran Voyager', category:'MINIVAN', size:'L', },
    { make:'Plymouth', model: 'Neon', category:'SEDAN', size:'S', },
    { make:'Plymouth', model: 'Prowler', category:'EXOTIC', size:'E', },
    { make:'Plymouth', model: 'Voyager', category:'MINIVAN', size:'L', },
    
    { make:'Pontiac', model: 'Aztek', category:'SUV', size:'L', },
    { make:'Pontiac', model: 'Bonneville', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'Firebird', category:'COUPE', size:'M', },
    { make:'Pontiac', model: 'G3', category:'SEDAN', size:'S', },
    { make:'Pontiac', model: 'G5', category:'COUPE', size:'S', },
    { make:'Pontiac', model: 'G6', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'G8', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'Grand Am', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'Grand Prix', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'GTO', category:'COUPE', size:'L', },
    { make:'Pontiac', model: 'Montana', category:'MINIVAN', size:'L', },
    { make:'Pontiac', model: 'Solstice', category:'COUPE', size:'S', },
    { make:'Pontiac', model: 'Sunfire', category:'SEDAN', size:'S', },
    { make:'Pontiac', model: 'Torrent', category:'SUV', size:'L', },
    { make:'Pontiac', model: 'Trans Sport', category:'MINIVAN', size:'L', },
    { make:'Pontiac', model: '', category:'SEDAN', size:'S', },

    { make:'Porsche', model: '356-Replica', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '550-Replica', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911', category:'COUPE', size:'L', },
    { make:'Porsche', model: '911 GT2', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911 GT3', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911 GTS', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911 TURBO', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '918 Spyder', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Boxter', category:'COUPE', size:'L', },
    { make:'Porsche', model: 'Boxter GTS / Spyder', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Carrera GT', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Cayenne', category:'SUV', size:'L', },
    { make:'Porsche', model: 'Cayenne GTS', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Cayenne Turbo', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Cayman', category:'COUPE', size:'L', },
    { make:'Porsche', model: 'Cayman GTS', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Macan', category:'SUV', size:'L', },
    { make:'Porsche', model: 'Macan GTS', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Macan Turbo', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Mission E', category:'SEDAN', size:'E', },
    { make:'Porsche', model: 'Panamera', category:'SEDAN', size:'L', },
    { make:'Porsche', model: 'Panamera GTS', category:'SEDAN', size:'E', },
    { make:'Porsche', model: 'Panamera Turbo', category:'SEDAN', size:'E', },

    { make:'Rolls-Royce', model: 'Culliman', category:'SUV', size:'E', },
    { make:'Rolls-Royce', model: 'Ghost', category:'SEDAN', size:'E', },
    { make:'Rolls-Royce', model: 'Phantom', category:'SEDAN', size:'E', },
    { make:'Rolls-Royce', model: 'Wraith', category:'EXOTIC', size:'E', },

    { make:'Rossion', model: 'Q1', category:'EXOTIC', size:'E', },

    { make:'Ruf', model: 'CTR3', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'R Turbo', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'RGT', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'RK', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'RT12', category:'EXOTIC', size:'E', },

    { make:'Saab', model: '9-2X', category:'SEDAN', size:'M', },
    { make:'Saab', model: '9-3.', category:'SEDAN', size:'M', },
    { make:'Saab', model: '9-4X', category:'SUV', size:'L', },
    { make:'Saab', model: '9-5.', category:'SEDAN', size:'M', },
    { make:'Saab', model: '9-7X', category:'SUV', size:'L', },

    { make:'Saleen', model: 'S7', category:'EXOTIC', size:'E', },

    { make:'Saturn', model: 'Astra', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Aura', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'ION', category:'SEDAN', size:'S', },
    { make:'Saturn', model: 'L-Series', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Outlook', category:'SEDAN', size:'L', },
    { make:'Saturn', model: 'Relay', category:'SEDAN', size:'L', },
    { make:'Saturn', model: 'S-Series', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Sky', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Vue', category:'SEDAN', size:'L', },

    { make:'Scion', model: 'FR-S', category:'COUPE', size:'S', },
    { make:'Scion', model: 'iA', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'iM', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'iQ', category:'COUPE', size:'S', },
    { make:'Scion', model: 'tC', category:'COUPE', size:'S', },
    { make:'Scion', model: 'xA', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'xB', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'xD', category:'SEDAN', size:'S', },

    { make:'Shelby', model: 'Cobra', category:'Exotic', size:'E', },

    { make:'Smart', model: 'fortwo', category:'COUPE', size:'S', },

    { make:'Spyker', model: 'C8', category:'EXOTIC', size:'E', },

    { make:'Subaru', model: 'Ascent', category:'SUV', size:'L', },
    { make:'Subaru', model: 'Baja', category:'TRUCK', size:'L', },
    { make:'Subaru', model: 'BRZ', category:'COUPE', size:'S', },
    { make:'Subaru', model: 'Forester', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Impreza', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Impreza WRX', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Legacy', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Outback', category:'SEDAN', size:'L', },
    { make:'Subaru', model: 'Tribeca', category:'SUV', size:'L', },
    { make:'Subaru', model: 'XV Crosstrek', category:'SEDAN', size:'M', },

    { make:'Suzuki', model: 'Aerio', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Equator', category:'TRUCK', size:'L', },
    { make:'Suzuki', model: 'Esteem', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Forenza', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Gran Vitara', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'Kizashi', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Reno', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Swift', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'SX4', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'Verona', category:'SEDAN', size:'M', },
    { make:'Suzuki', model: 'Vitara', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'X-90', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'XL7', category:'SUV', size:'L', },

    { make:'Tesla', model: 'Model 3', category:'SEDAN', size:'L', },
    { make:'Tesla', model: 'Model S', category:'SEDAN', size:'L', },
    { make:'Tesla', model: 'Model X', category:'SUV', size:'E', },
    { make:'Tesla', model: 'Model Y', category:'SUV', size:'E', },
    { make:'Tesla', model: 'Roadster', category:'EXOTIC', size:'E', },

    { make:'Toyota', model: '4Runner', category:'SUV', size:'L', },
    { make:'Toyota', model: '86', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Avalon', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'C-HR', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Camry', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'Celica', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Corolla', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Echo', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'FJ Cruiser', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Highlander', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Hilux', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Land Cruiser', category:'SUV', size:'E', },
    { make:'Toyota', model: 'Matrix', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Mirai', category:'SEDAN', size:'L', },
    { make:'Toyota', model: 'MR2', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'MR2 Spyder', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Paseo', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Prius', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'Prius C', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Prius V', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'RAV4', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Sequoia', category:'SUV', size:'E', },
    { make:'Toyota', model: 'Sienna', category:'MINIVAN', size:'L', },
    { make:'Toyota', model: 'Solara', category:'COUPE', size:'M', },
    { make:'Toyota', model: 'Supra', category:'COUPE', size:'L', },
    { make:'Toyota', model: 'T100', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Tacoma', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Tercel', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Tundra', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Venza', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Yaris', category:'SEDAN', size:'S', },

    { make:'TVR', model: 'Cerbera', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Chimaera', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Sagaris', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'T350', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Tamora', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Tuscan', category:'EXOTIC', size:'E', },

    { make:'Vector', model: 'W8', category:'EXOTIC', size:'E', },

    { make:'Volkswagen', model: 'Arteon', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Atlas', category:'SUV', size:'E', },
    { make:'Volkswagen', model: 'Beetle', category:'COUPE', size:'M', },
    { make:'Volkswagen', model: 'Cabrio', category:'COUPE', size:'S', },
    { make:'Volkswagen', model: 'CC', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Eos', category:'COUPE', size:'M', },
    { make:'Volkswagen', model: 'Eurovan', category:'MINIVAN', size:'L', },
    { make:'Volkswagen', model: 'Fox', category:'SEDAN', size:'S', },
    { make:'Volkswagen', model: 'Golf', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Golf R', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Jetta', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Passat', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Phaeton', category:'SEDAN', size:'L', },
    { make:'Volkswagen', model: 'Pickup', category:'TRUCK', size:'L', },
    { make:'Volkswagen', model: 'Routan', category:'MINIVAN', size:'L', },
    { make:'Volkswagen', model: 'Tiguan', category:'SUV', size:'L', },
    { make:'Volkswagen', model: 'Touareg', category:'SUV', size:'L', },
    { make:'Volkswagen', model: 'Vanagon', category:'MINIVAN', size:'L', },

    { make:'Volvo', model: '960', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'C30', category:'COUPE', size:'M', },
    { make:'Volvo', model: 'C70', category:'COUPE', size:'M', },
    { make:'Volvo', model: 'S40', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S60', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S70', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S80', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S90', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V40', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V50', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V60', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V70', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V90', category:'SEDAN', size:'L', },
    { make:'Volvo', model: 'XC40', category:'SUV', size:'L', },
    { make:'Volvo', model: 'XC60', category:'SUV', size:'L', },
    { make:'Volvo', model: 'XC70', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'XC90', category:'SUV', size:'L', },
    
  ]);
};
