
exports.seed = function(knex) {
  return knex('cars').insert([
    { make:'Ford', model: 'Aerostar', category:'MINIVAN', size:'L', },
    { make:'Ford', model: 'Aspire', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Bronco', category:'SUV', size:'L', },
    { make:'Ford', model: 'Bronco II', category:'SUV', size:'L', },
    { make:'Ford', model: 'C-MAX', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'Contour', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Courier', category:'TRUCK', size:'S', },
    { make:'Ford', model: 'Crown Victoria', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'E-150', category:'VAN', size:'E', },
    { make:'Ford', model: 'E-250', category:'VAN', size:'E', },
    { make:'Ford', model: 'E-350', category:'VAN', size:'E', },
    { make:'Ford', model: 'Ecosport', category:'SUV', size:'M', },
    { make:'Ford', model: 'Edge', category:'SUV', size:'L', },
    { make:'Ford', model: 'Escape', category:'SUV', size:'L', },
    { make:'Ford', model: 'Escort', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Excursion', category:'SUV', size:'E', },
    { make:'Ford', model: 'EXP', category:'COUPE', size:'S', },
    { make:'Ford', model: 'Expedition', category:'SUV', size:'E', },
    { make:'Ford', model: 'Expedition EL', category:'SUV', size:'E', },
    { make:'Ford', model: 'Explorer', category:'SUV', size:'L', },
    { make:'Ford', model: 'Explorer Sport Trac', category:'TRUCK', size:'L', },
    { make:'Ford', model: 'F-150', category:'TRUCK', size:'L', },
    { make:'Ford', model: 'F-250', category:'TRUCK', size:'E', },
    { make:'Ford', model: 'F-350', category:'TRUCK', size:'E', },
    { make:'Ford', model: 'Festiva', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Fiesta', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Five Hundred', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'Flex', category:'SUV', size:'L', },
    { make:'Ford', model: 'Focus', category:'SEDAN', size:'S', },
    { make:'Ford', model: 'Freestyle', category:'MINIVAN', size:'L', },
    { make:'Ford', model: 'Fusion', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'GT', category:'EXOTIC', size:'E', },
    { make:'Ford', model: 'GT40-Replica', category:'EXOTIC', size:'E', },
    { make:'Ford', model: 'Mustang', category:'COUPE', size:'M', },
    { make:'Ford', model: 'Ranger', category:'TRUCK', size:'L', },
    { make:'Ford', model: 'Raptor', category:'TRUCK', size:'E', },
    { make:'Ford', model: 'Taurus', category:'SEDAN', size:'M', },
    { make:'Ford', model: 'Taurus X', category:'SUV', size:'L', },
    { make:'Ford', model: 'Thunderbird', category:'COUPE', size:'M', },
    { make:'Ford', model: 'Transit Connect', category:'MINIVAN', size:'E', },
    { make:'Ford', model: 'Windstar', category:'MINIVAN', size:'L', },
    { make:'Ford', model: 'ZX2 Escort', category:'COUPE', size:'S', },
    
    { make:'Genesis', model: 'G70', category:'SEDAN', size:'L', },
    { make:'Genesis', model: 'G80', category:'SEDAN', size:'L', },
    { make:'Genesis', model: 'G90', category:'SEDAN', size:'L', },

    { make:'Geo', model: 'Metro', category:'SEDAN', size:'S', },
    { make:'Geo', model: 'Prism', category:'SEDAN', size:'S', },
    { make:'Geo', model: 'Spectrum', category:'SEDAN', size:'S', },
    { make:'Geo', model: 'Storm', category:'COUPE', size:'S', },
    { make:'Geo', model: 'Tracker', category:'SUV', size:'L', },

    { make:'GMC', model: 'Acadia', category:'SUV', size:'L', },
    { make:'GMC', model: 'Canyon', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Envoy', category:'SUV', size:'L', },
    { make:'GMC', model: 'Envoy XL', category:'SUV', size:'L', },
    { make:'GMC', model: 'Envoy XUV', category:'SUV', size:'L', },
    { make:'GMC', model: 'G1500', category:'VAN', size:'E', },
    { make:'GMC', model: 'G2500', category:'VAN', size:'E', },
    { make:'GMC', model: 'G3500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Jimmy', category:'SUV', size:'L', },
    { make:'GMC', model: 'S15 Jimmy', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'S15 Pickup', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Safari', category:'MINIVAN', size:'L', },
    { make:'GMC', model: 'Savana 1500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Savana 2500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Savana 3500', category:'VAN', size:'E', },
    { make:'GMC', model: 'Sierra 1500', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Sierra 2500', category:'TRUCK', size:'E', },
    { make:'GMC', model: 'Sierra 3500', category:'TRUCK', size:'E', },
    { make:'GMC', model: 'Sonoma', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Suburban', category:'SUV', size:'E', },
    { make:'GMC', model: 'Syclone', category:'TRUCK', size:'L', },
    { make:'GMC', model: 'Terrain', category:'SUV', size:'L', },
    { make:'GMC', model: 'Typhoon', category:'SUV', size:'L', },
    { make:'GMC', model: 'Yukon', category:'SUV', size:'L', },
    { make:'GMC', model: 'Yukon XL', category:'SUV', size:'E', },

    { make:'Honda', model: 'Accord', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'Accord Crosstour', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'Civic', category:'SEDAN', size:'S', },
    { make:'Honda', model: 'Clarity', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'CR-V', category:'SUV', size:'L', },
    { make:'Honda', model: 'CR-Z', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Crosstour', category:'SEDAN', size:'M', },
    { make:'Honda', model: 'CRX', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Del Sol', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Element', category:'SUV', size:'L', },
    { make:'Honda', model: 'Fit', category:'SEDAN', size:'S', },
    { make:'Honda', model: 'HR-V', category:'SUV', size:'L', },
    { make:'Honda', model: 'Insight', category:'SEDAN', size:'S', },
    { make:'Honda', model: 'Odyssey', category:'MINIVAN', size:'L', },
    { make:'Honda', model: 'Passport', category:'SUV', size:'L', },
    { make:'Honda', model: 'Pilot', category:'SUV', size:'L', },
    { make:'Honda', model: 'Prelude', category:'COUPE', size:'S', },
    { make:'Honda', model: 'Ridgeline', category:'TRUCK', size:'L', },
    { make:'Honda', model: 'S2000', category:'COUPE', size:'M', },

    { make:'Hummer', model: 'H1', category:'SUV', size:'E', },
    { make:'Hummer', model: 'H2', category:'SUV', size:'E', },
    { make:'Hummer', model: 'H3', category:'SUV', size:'L', },
    { make:'Hummer', model: 'H3T', category:'TRUCK', size:'L', },

    { make:'Hyundai', model: 'Accent', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Azera', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Elantra', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Elantra Coupe', category:'COUPE', size:'S', },
    { make:'Hyundai', model: 'Elantra GT', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Elantra Touring', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Entourage', category:'MINIVAN', size:'L', },
    { make:'Hyundai', model: 'Equus', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Excel', category:'SEDAN', size:'S', },
    { make:'Hyundai', model: 'Genesis', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Genesis Coupe', category:'COUPE', size:'M', },
    { make:'Hyundai', model: 'Ioniq', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Kona', category:'SUV', size:'M', },
    { make:'Hyundai', model: 'Nexo', category:'SUV', size:'M', },
    { make:'Hyundai', model: 'Palisade', category:'SUV', size:'E', },
    { make:'Hyundai', model: 'Santa Fe', category:'SUV', size:'L', },
    { make:'Hyundai', model: 'S Coupe', category:'COUPE', size:'S', },
    { make:'Hyundai', model: 'Sonata', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'Tiburon', category:'COUPE', size:'S', },
    { make:'Hyundai', model: 'Tucson', category:'SUV', size:'L', },
    { make:'Hyundai', model: 'Veloster', category:'COUPE', size:'M', },
    { make:'Hyundai', model: 'Veracruz', category:'SUV', size:'L', },
    { make:'Hyundai', model: 'XG300', category:'SEDAN', size:'M', },
    { make:'Hyundai', model: 'XG350', category:'SEDAN', size:'M', },

    { make:'Infiniti', model: 'EX35', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'EX37', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX35', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX37', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX45', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'FX50', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'G20', category:'SEDAN', size:'S', },
    { make:'Infiniti', model: 'G25', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'G35', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'G37', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'I30', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'I35', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'J30', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'JX35', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'M30', category:'COUPE', size:'M', },
    { make:'Infiniti', model: 'M35', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'M35h', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'M37', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'M45', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'M56', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'Q40', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q45', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q50', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q60', category:'SEDAN', size:'M', },
    { make:'Infiniti', model: 'Q70', category:'SEDAN', size:'L', },
    { make:'Infiniti', model: 'QX30', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX4', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX50', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX56', category:'SUV', size:'E', },
    { make:'Infiniti', model: 'QX60', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX70', category:'SUV', size:'L', },
    { make:'Infiniti', model: 'QX80', category:'SUV', size:'E', },

    { make:'Isuzu', model: 'Amigo', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Ascender', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Axiom', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Hombre', category:'TRUCK', size:'L', },
    { make:'Isuzu', model: 'I-Mark', category:'COUPE', size:'M', },
    { make:'Isuzu', model: 'Impulse', category:'COUPE', size:'S', },
    { make:'Isuzu', model: 'Oasis', category:'MINIVAN', size:'L', },
    { make:'Isuzu', model: 'Rodeo', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Stylus', category:'SEDAN', size:'S', },
    { make:'Isuzu', model: 'Trooper', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'Trooper II', category:'SUV', size:'L', },
    { make:'Isuzu', model: 'VehiCROSS', category:'SUV', size:'L', },

    { make:'Jaguar', model: 'E-Pace', category:'SUV', size:'L', },
    { make:'Jaguar', model: 'F-Pace', category:'SUV', size:'L', },
    { make:'Jaguar', model: 'F-Type', category:'COUPE', size:'M', },
    { make:'Jaguar', model: 'I-Pace', category:'SUV', size:'L', },
    { make:'Jaguar', model: 'S-Type', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'X-Type', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XE', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XF', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XF SportBrake', category:'SEDAN', size:'M', },
    { make:'Jaguar', model: 'XJ', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ Sport', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ Vanden Plus', category:'', size:'L', },
    { make:'Jaguar', model: 'XJ12', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ6', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ8', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJ8 L', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJR', category:'SEDAN', size:'L', },
    { make:'Jaguar', model: 'XJR-S', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XJS', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XK', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XK8', category:'COUPE', size:'L', },
    { make:'Jaguar', model: 'XKR', category:'COUPE', size:'L', },

  ]);
};