
exports.seed = function(knex) {
  return knex('cars').insert([
    { make:'Oldsmobile', model: 'Achieva', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Alero', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Aurora', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Bravada', category:'SEDAN', size:'L', },
    { make:'Oldsmobile', model: 'Cutlass', category:'SEDAN', size:'M', },
    { make:'Oldsmobile', model: 'Cutlass Supreme', category:'SEDAN', size:'M', },
    { make:'Oldsmobile', model: 'Intrigue', category:'SEDAN', size:'S', },
    { make:'Oldsmobile', model: 'Silhouette', category:'MINIVAN', size:'L', },

    { make:'Plymouth', model: 'Breeze', category:'SEDAN', size:'S', },
    { make:'Plymouth', model: 'Gran Voyager', category:'MINIVAN', size:'L', },
    { make:'Plymouth', model: 'Neon', category:'SEDAN', size:'S', },
    { make:'Plymouth', model: 'Prowler', category:'EXOTIC', size:'E', },
    { make:'Plymouth', model: 'Voyager', category:'MINIVAN', size:'L', },
    
    { make:'Pontiac', model: 'Aztek', category:'SUV', size:'L', },
    { make:'Pontiac', model: 'Bonneville', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'Firebird', category:'COUPE', size:'M', },
    { make:'Pontiac', model: 'G3', category:'SEDAN', size:'S', },
    { make:'Pontiac', model: 'G5', category:'COUPE', size:'S', },
    { make:'Pontiac', model: 'G6', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'G8', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'Grand Am', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'Grand Prix', category:'SEDAN', size:'M', },
    { make:'Pontiac', model: 'GTO', category:'COUPE', size:'L', },
    { make:'Pontiac', model: 'Montana', category:'MINIVAN', size:'L', },
    { make:'Pontiac', model: 'Solstice', category:'COUPE', size:'S', },
    { make:'Pontiac', model: 'Sunfire', category:'SEDAN', size:'S', },
    { make:'Pontiac', model: 'Torrent', category:'SUV', size:'L', },
    { make:'Pontiac', model: 'Trans Sport', category:'MINIVAN', size:'L', },
    { make:'Pontiac', model: '', category:'SEDAN', size:'S', },

    { make:'Porsche', model: '356-Replica', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '550-Replica', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911', category:'COUPE', size:'L', },
    { make:'Porsche', model: '911 GT2', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911 GT3', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911 GTS', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '911 TURBO', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: '918 Spyder', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Boxter', category:'COUPE', size:'L', },
    { make:'Porsche', model: 'Boxter GTS / Spyder', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Carrera GT', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Cayenne', category:'SUV', size:'L', },
    { make:'Porsche', model: 'Cayenne GTS', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Cayenne Turbo', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Cayman', category:'COUPE', size:'L', },
    { make:'Porsche', model: 'Cayman GTS', category:'EXOTIC', size:'E', },
    { make:'Porsche', model: 'Macan', category:'SUV', size:'L', },
    { make:'Porsche', model: 'Macan GTS', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Macan Turbo', category:'SUV', size:'E', },
    { make:'Porsche', model: 'Mission E', category:'SEDAN', size:'E', },
    { make:'Porsche', model: 'Panamera', category:'SEDAN', size:'L', },
    { make:'Porsche', model: 'Panamera GTS', category:'SEDAN', size:'E', },
    { make:'Porsche', model: 'Panamera Turbo', category:'SEDAN', size:'E', },

    { make:'Rolls-Royce', model: 'Culliman', category:'SUV', size:'E', },
    { make:'Rolls-Royce', model: 'Ghost', category:'SEDAN', size:'E', },
    { make:'Rolls-Royce', model: 'Phantom', category:'SEDAN', size:'E', },
    { make:'Rolls-Royce', model: 'Wraith', category:'EXOTIC', size:'E', },

    { make:'Rossion', model: 'Q1', category:'EXOTIC', size:'E', },

    { make:'Ruf', model: 'CTR3', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'R Turbo', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'RGT', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'RK', category:'EXOTIC', size:'E', },
    { make:'Ruf', model: 'RT12', category:'EXOTIC', size:'E', },

    { make:'Saab', model: '9-2X', category:'SEDAN', size:'M', },
    { make:'Saab', model: '9-3.', category:'SEDAN', size:'M', },
    { make:'Saab', model: '9-4X', category:'SUV', size:'L', },
    { make:'Saab', model: '9-5.', category:'SEDAN', size:'M', },
    { make:'Saab', model: '9-7X', category:'SUV', size:'L', },

    { make:'Saleen', model: 'S7', category:'EXOTIC', size:'E', },

    { make:'Saturn', model: 'Astra', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Aura', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'ION', category:'SEDAN', size:'S', },
    { make:'Saturn', model: 'L-Series', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Outlook', category:'SEDAN', size:'L', },
    { make:'Saturn', model: 'Relay', category:'SEDAN', size:'L', },
    { make:'Saturn', model: 'S-Series', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Sky', category:'SEDAN', size:'M', },
    { make:'Saturn', model: 'Vue', category:'SEDAN', size:'L', },

    { make:'Scion', model: 'FR-S', category:'COUPE', size:'S', },
    { make:'Scion', model: 'iA', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'iM', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'iQ', category:'COUPE', size:'S', },
    { make:'Scion', model: 'tC', category:'COUPE', size:'S', },
    { make:'Scion', model: 'xA', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'xB', category:'SEDAN', size:'S', },
    { make:'Scion', model: 'xD', category:'SEDAN', size:'S', },

    { make:'Shelby', model: 'Cobra', category:'Exotic', size:'E', },

    { make:'Smart', model: 'fortwo', category:'COUPE', size:'S', },

    { make:'Spyker', model: 'C8', category:'EXOTIC', size:'E', },

    { make:'Subaru', model: 'Ascent', category:'SUV', size:'L', },
    { make:'Subaru', model: 'Baja', category:'TRUCK', size:'L', },
    { make:'Subaru', model: 'BRZ', category:'COUPE', size:'S', },
    { make:'Subaru', model: 'Forester', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Impreza', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Impreza WRX', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Legacy', category:'SEDAN', size:'M', },
    { make:'Subaru', model: 'Outback', category:'SEDAN', size:'L', },
    { make:'Subaru', model: 'Tribeca', category:'SUV', size:'L', },
    { make:'Subaru', model: 'XV Crosstrek', category:'SEDAN', size:'M', },

    { make:'Suzuki', model: 'Aerio', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Equator', category:'TRUCK', size:'L', },
    { make:'Suzuki', model: 'Esteem', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Forenza', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Gran Vitara', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'Kizashi', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Reno', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'Swift', category:'SEDAN', size:'S', },
    { make:'Suzuki', model: 'SX4', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'Verona', category:'SEDAN', size:'M', },
    { make:'Suzuki', model: 'Vitara', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'X-90', category:'SUV', size:'L', },
    { make:'Suzuki', model: 'XL7', category:'SUV', size:'L', },

    { make:'Tesla', model: 'Model 3', category:'SEDAN', size:'L', },
    { make:'Tesla', model: 'Model S', category:'SEDAN', size:'L', },
    { make:'Tesla', model: 'Model X', category:'SUV', size:'E', },
    { make:'Tesla', model: 'Model Y', category:'SUV', size:'E', },
    { make:'Tesla', model: 'Roadster', category:'EXOTIC', size:'E', },

    { make:'Toyota', model: '4Runner', category:'SUV', size:'L', },
    { make:'Toyota', model: '86', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Avalon', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'C-HR', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Camry', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'Celica', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Corolla', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Echo', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'FJ Cruiser', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Highlander', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Hilux', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Land Cruiser', category:'SUV', size:'E', },
    { make:'Toyota', model: 'Matrix', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Mirai', category:'SEDAN', size:'L', },
    { make:'Toyota', model: 'MR2', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'MR2 Spyder', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Paseo', category:'COUPE', size:'S', },
    { make:'Toyota', model: 'Prius', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'Prius C', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Prius V', category:'SEDAN', size:'M', },
    { make:'Toyota', model: 'RAV4', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Sequoia', category:'SUV', size:'E', },
    { make:'Toyota', model: 'Sienna', category:'MINIVAN', size:'L', },
    { make:'Toyota', model: 'Solara', category:'COUPE', size:'M', },
    { make:'Toyota', model: 'Supra', category:'COUPE', size:'L', },
    { make:'Toyota', model: 'T100', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Tacoma', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Tercel', category:'SEDAN', size:'S', },
    { make:'Toyota', model: 'Tundra', category:'TRUCK', size:'L', },
    { make:'Toyota', model: 'Venza', category:'SUV', size:'L', },
    { make:'Toyota', model: 'Yaris', category:'SEDAN', size:'S', },

    { make:'TVR', model: 'Cerbera', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Chimaera', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Sagaris', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'T350', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Tamora', category:'EXOTIC', size:'E', },
    { make:'TVR', model: 'Tuscan', category:'EXOTIC', size:'E', },

    { make:'Vector', model: 'W8', category:'EXOTIC', size:'E', },

    { make:'Volkswagen', model: 'Arteon', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Atlas', category:'SUV', size:'E', },
    { make:'Volkswagen', model: 'Beetle', category:'COUPE', size:'M', },
    { make:'Volkswagen', model: 'Cabrio', category:'COUPE', size:'S', },
    { make:'Volkswagen', model: 'CC', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Eos', category:'COUPE', size:'M', },
    { make:'Volkswagen', model: 'Eurovan', category:'MINIVAN', size:'L', },
    { make:'Volkswagen', model: 'Fox', category:'SEDAN', size:'S', },
    { make:'Volkswagen', model: 'Golf', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Golf R', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Jetta', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Passat', category:'SEDAN', size:'M', },
    { make:'Volkswagen', model: 'Phaeton', category:'SEDAN', size:'L', },
    { make:'Volkswagen', model: 'Pickup', category:'TRUCK', size:'L', },
    { make:'Volkswagen', model: 'Routan', category:'MINIVAN', size:'L', },
    { make:'Volkswagen', model: 'Tiguan', category:'SUV', size:'L', },
    { make:'Volkswagen', model: 'Touareg', category:'SUV', size:'L', },
    { make:'Volkswagen', model: 'Vanagon', category:'MINIVAN', size:'L', },

    { make:'Volvo', model: '960', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'C30', category:'COUPE', size:'M', },
    { make:'Volvo', model: 'C70', category:'COUPE', size:'M', },
    { make:'Volvo', model: 'S40', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S60', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S70', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S80', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'S90', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V40', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V50', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V60', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V70', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'V90', category:'SEDAN', size:'L', },
    { make:'Volvo', model: 'XC40', category:'SUV', size:'L', },
    { make:'Volvo', model: 'XC60', category:'SUV', size:'L', },
    { make:'Volvo', model: 'XC70', category:'SEDAN', size:'M', },
    { make:'Volvo', model: 'XC90', category:'SUV', size:'L', },
  ]);
};