exports.seed = function(knex, Promise) {
  return knex('cars').insert([
    { make:'Jeep', model: 'Cherokee', category:'SUV', size:'L', },
    { make:'Jeep', model: 'CJ', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Comanche', category:'TRUCK', size:'L', },
    { make:'Jeep', model: 'Commander', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Compass', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Gladiator', category:'TRUCK', size:'E', },
    { make:'Jeep', model: 'Grand Cherokee', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Grand Wagoneer', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Liberty', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Patriot', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Pickup', category:'TRUCK', size:'L', },
    { make:'Jeep', model: 'Renegade', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Scrambler', category:'SUV', size:'L', },
    { make:'Jeep', model: 'Wagoneer', category:'SUV', size:'E', },
    { make:'Jeep', model: 'Wrangler', category:'SUV', size:'L', },

    { make:'Kia', model: 'Amanti', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Borrego', category:'SUV', size:'L', },
    { make:'Kia', model: 'Cadenza', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Forte', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Forte Koup', category:'COUPE', size:'S', },
    { make:'Kia', model: 'K900', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Niro', category:'SUV', size:'L', },
    { make:'Kia', model: 'Optima', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Rio', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Rio5', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Rondo', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Sedona', category:'MINIVAN', size:'L', },
    { make:'Kia', model: 'Sephia', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Sorento', category:'SUV', size:'L', },
    { make:'Kia', model: 'Soul', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Spectra', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Spectra5', category:'SEDAN', size:'S', },
    { make:'Kia', model: 'Sportage', category:'SUV', size:'L', },
    { make:'Kia', model: 'Stinger', category:'SEDAN', size:'M', },
    { make:'Kia', model: 'Telluride', category:'SUV', size:'E', },

    { make:'Koenigsegg', model: 'CCR', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'CCS8', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'CCX', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'CCXR', category:'EXOTIC', size:'E', },
    { make:'Koenigsegg', model: 'Regera', category:'EXOTIC', size:'E', },

    { make:'Lamborghini', model: 'Aventador', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Countach', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Countach-Replica', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Diablo', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Diablo-Replica', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Gallardo', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Huracan', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Jalpa', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'LM002', category:'SUV', size:'E', },
    { make:'Lamborghini', model: 'Murcielago', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Murcielago-Replica', category:'EXOTIC', size:'E', },
    { make:'Lamborghini', model: 'Urus', category:'SUV', size:'E', },

    { make:'Land Rover', model: 'Defender', category:'SUV', size:'E', },
    { make:'Land Rover', model: 'Discovery', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Discovery Sport', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Freelander', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'LR2', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'LR3', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'LR4', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Range Rover', category:'SUV', size:'E', },
    { make:'Land Rover', model: 'Range Rover Evoque', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Range Rover Sport', category:'SUV', size:'L', },
    { make:'Land Rover', model: 'Range Rover Velar', category:'SUV', size:'E', },

    { make:'Lexus', model: 'CT 200h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 250', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 300', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 300h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 330', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'ES 350', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 200t', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 300', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 350', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 400', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 430', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 450h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GS 460', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'GX 460', category:'SUV', size:'L', },
    { make:'Lexus', model: 'GX 470', category:'SUV', size:'L', },
    { make:'Lexus', model: 'HS 250h', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 200t', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 250', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 250c', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'IS 300', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 350', category:'SEDAN', size:'M', },
    { make:'Lexus', model: 'IS 350c', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'IS F', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LC 500', category:'COUPE', size:'E', },
    { make:'Lexus', model: 'LFA', category:'EXOTIC', size:'E', },
    { make:'Lexus', model: 'LS', category:'SUV', size:'E', },
    { make:'Lexus', model: 'LS 400', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LS 430', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LS 460', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LS 500', category:'SEDAN', size:'E', },
    { make:'Lexus', model: 'LS 600h', category:'SEDAN', size:'L', },
    { make:'Lexus', model: 'LX 450', category:'SUV', size:'E', },
    { make:'Lexus', model: 'LX 470', category:'SUV', size:'E', },
    { make:'Lexus', model: 'LX 570', category:'SUV', size:'E', },
    { make:'Lexus', model: 'NX 200t', category:'SUV', size:'L', },
    { make:'Lexus', model: 'NX 300h', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RC 350', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'RC F', category:'COUPE', size:'L', },
    { make:'Lexus', model: 'RX 300', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 330', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 350', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 350L', category:'SUV', size:'E', },
    { make:'Lexus', model: 'RX 400h', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 450h', category:'SUV', size:'L', },
    { make:'Lexus', model: 'RX 450HL', category:'SUV', size:'E', },
    { make:'Lexus', model: 'SC 300', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'SC 400', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'SC 430', category:'COUPE', size:'M', },
    { make:'Lexus', model: 'UX', category:'SUV', size:'L', },

    { make:'Lincoln', model: 'Aviator', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'Blackwood', category:'TRUCK', size:'L', },
    { make:'Lincoln', model: 'Continental', category:'SEDAN', size:'L', },
    { make:'Lincoln', model: 'LS', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'Mark LT', category:'TRUCK', size:'L', },
    { make:'Lincoln', model: 'MKC', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'MKS', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'MKT', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'MKX', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'MKZ', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'Nautilus', category:'SUV', size:'L', },
    { make:'Lincoln', model: 'Navigator', category:'SUV', size:'E', },
    { make:'Lincoln', model: 'Navigator L', category:'SUV', size:'E', },
    { make:'Lincoln', model: 'Town Car', category:'SEDAN', size:'M', },
    { make:'Lincoln', model: 'Zephyr', category:'SEDAN', size:'M', },

    { make:'Lotus', model: 'Elise', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Elite', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Espirit', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Evora', category:'EXOTIC', size:'E', },
    { make:'Lotus', model: 'Exige', category:'EXOTIC', size:'E', },

    { make:'Maserati', model: '430', category:'SEDAN', size:'L', },
    { make:'Maserati', model: 'BiTurbo', category:'EXOTIC', size:'E', },
    { make:'Maserati', model: 'Ghibli', category:'SEDAN', size:'L', },
    { make:'Maserati', model: 'GranSport', category:'EXOTIC', size:'E', },
    { make:'Maserati', model: 'GranTourismo', category:'EXOTIC', size:'E', },
    { make:'Maserati', model: 'Levante', category:'SUV', size:'E', },
    { make:'Maserati', model: 'Quattroporte', category:'SEDAN', size:'L', },
    { make:'Maserati', model: 'Spyder', category:'EXOTIC', size:'E', },

    { make:'Maybach', model: '57', category:'SEDAN', size:'E', },
    { make:'Maybach', model: '62', category:'SEDAN', size:'E', },
    { make:'Maybach', model: '62S Landaulet', category:'SEDAN', size:'E', },

    { make:'Mazda', model: '323', category:'SEDAN', size:'S', },
    { make:'Mazda', model: '626', category:'SEDAN', size:'M', },
    { make:'Mazda', model: '929', category:'SEDAN', size:'M', },
    { make:'Mazda', model: 'B-Series Pickup', category:'TRUCK', size:'L', },
    { make:'Mazda', model: 'CX-3', category:'SUV', size:'L', },
    { make:'Mazda', model: 'CX-5', category:'SUV', size:'L', },
    { make:'Mazda', model: 'CX-7', category:'SUV', size:'L', },
    { make:'Mazda', model: 'CX-9', category:'SUV', size:'L', },
    { make:'Mazda', model: 'Mazda2', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Mazda3', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Mazda5', category:'MINIVAN', size:'L', },
    { make:'Mazda', model: 'Mazda6', category:'SEDAN', size:'M', },
    { make:'Mazda', model: 'Mazdaspeed3', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Mazdaspeed6', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Millenia', category:'SEDAN', size:'M', },
    { make:'Mazda', model: 'MPV', category:'MINIVAN', size:'L', },
    { make:'Mazda', model: 'MX-5 Miata', category:'COUPE', size:'M', },
    { make:'Mazda', model: 'MX3', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'MX6', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'Protege', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'Protege5', category:'SEDAN', size:'S', },
    { make:'Mazda', model: 'RX-7', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'RX-8', category:'COUPE', size:'S', },
    { make:'Mazda', model: 'Tribute', category:'SUV', size:'L', },

    { make:'McLaren', model: '570S', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: '650S', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: '675LT', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: '720S', category:'COUPE', size:'E', },
    { make:'McLaren', model: 'F1', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: 'Hypercar', category:'COUPE', size:'E', },
    { make:'McLaren', model: 'MP4-12C', category:'EXOTIC', size:'E', },
    { make:'McLaren', model: 'P1', category:'EXOTIC', size:'E', },
  ]);
};
