exports.seed = function(knex, Promise) {
  return knex('cars').insert([
    { make:'Mercedes-Benz', model: '400SEL', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: '500SL', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: '600SL', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'A220', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'AMG GT', category:'EXOTIC', size:'E', },
    { make:'Mercedes-Benz', model: 'B-Class Electric Drive', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'C220', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C230', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C240', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C250', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C280', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C300', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C32 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C320', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C350', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C36 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C400', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C43 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C450', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'C55 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'C63 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CL500', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL550', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL600', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL500', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL550', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL600', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CL65 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CLA250', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'CLA45 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLK320', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK350', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK430', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK500', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CLK550', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'CLK63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS400', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS450', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS500', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'CLS63 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'E250', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E300', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E320', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E350', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E400', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E43 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'E450', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E500', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E55 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'E550', category:'SEDAN', size:'M', },
    { make:'Mercedes-Benz', model: 'E63 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'EQC400', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'G500', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'G55 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'G550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'G63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL320', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL350', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL450', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GL63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLA250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLA45 AMG', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLC300', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLC350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLC43 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLC63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLE300d', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE400', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE43 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLE450', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLE550e', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLE63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLK250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLK350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLS350d', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 450', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 580', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLK250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLK350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'GLS 350d', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 450', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 550', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 580', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'GLS 63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'Maybach S600', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'Metris', category:'VAN', size:'L', },
    { make:'Mercedes-Benz', model: 'ML250', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML320', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML400', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML430', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML450', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML500', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML55 AMG', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML550', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'ML63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'R320', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'R350', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'R500', category:'SUV', size:'L', },
    { make:'Mercedes-Benz', model: 'R63 AMG', category:'SUV', size:'E', },
    { make:'Mercedes-Benz', model: 'S320', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S350', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S400', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S420', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S430', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S450', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S500', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S55 AMG', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S550', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S560', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S600', category:'SEDAN', size:'L', },
    { make:'Mercedes-Benz', model: 'S63 AMG', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'S65 AMG', category:'SEDAN', size:'E', },
    { make:'Mercedes-Benz', model: 'SL20', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL400', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL550', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL600', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL63 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SL65 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLC43 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLK230', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK250', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK280', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK300', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK32 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLK320', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK350', category:'COUPE', size:'M', },
    { make:'Mercedes-Benz', model: 'SLK55 AMG', category:'COUPE', size:'L', },
    { make:'Mercedes-Benz', model: 'SLR', category:'EXOTIC', size:'E', },
    { make:'Mercedes-Benz', model: 'SLS AMG', category:'EXOTIC', size:'E', },

    { make:'Mercury', model: 'Grand Marquis', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Mariner', category:'SEDAN', size:'L', },
    { make:'Mercury', model: 'Maurader', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Montego', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Mountaineer', category:'SEDAN', size:'L', },
    { make:'Mercury', model: 'Mystique', category:'SEDAN', size:'S', },
    { make:'Mercury', model: 'Sable', category:'SEDAN', size:'M', },
    { make:'Mercury', model: 'Tracer', category:'SEDAN', size:'S', },
    { make:'Mercury', model: 'Villager', category:'SEDAN', size:'L', },
    { make:'Mercury', model: 'Voyager', category:'SEDAN', size:'L', },

    { make:'MINI', model: 'Cooper', category:'COUPE', size:'M', },
    { make:'MINI', model: 'Cooper Clubman', category:'SEDAN', size:'M', },
    { make:'MINI', model: 'Cooper Countryman', category:'SEDAN', size:'M', },
    { make:'MINI', model: 'Cooper Coupe', category:'COUPE', size:'M', },
    { make:'MINI', model: 'Cooper Cooper Paceman', category:'COUPE', size:'M', },
    { make:'MINI', model: 'Cooper Cooper Roadster', category:'COUPE', size:'M', },

    { make:'Mitsubishi', model: '300GT', category:'COUPE', size:'M', },
    { make:'Mitsubishi', model: 'Diamante', category:'SEDAN', size:'M', },
    { make:'Mitsubishi', model: 'Eclipse', category:'COUPE', size:'S', },
    { make:'Mitsubishi', model: 'Eclipse Cross', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Endeavor', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Expo', category:'MINIVAN', size:'L', },
    { make:'Mitsubishi', model: 'Galant', category:'SEDAN', size:'M', },
    { make:'Mitsubishi', model: 'i', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'i-MiEV', category:'SEDAN', size:'M', },
    { make:'Mitsubishi', model: 'Lancer', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'Lancer Evolution', category:'SEDAN', size:'L', },
    { make:'Mitsubishi', model: 'Mighty Max', category:'TRUCK', size:'L', },
    { make:'Mitsubishi', model: 'Mirage', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'Montero', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Montero Sport', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Outlander', category:'SUV', size:'L', },
    { make:'Mitsubishi', model: 'Precis', category:'SEDAN', size:'S', },
    { make:'Mitsubishi', model: 'Raider', category:'TRUCK', size:'L', },
    { make:'Mitsubishi', model: 'Starion', category:'COUPE', size:'S', },

    { make:'Morgan', model: 'Aero 8', category:'EXOTIC', size:'E', },
    { make:'Morgan', model: 'Super Sports', category:'EXOTIC', size:'E', },

    { make:'Mosler', model: 'MT900', category:'EXOTIC', size:'E', },
    
    { make:'Nissan', model: '200SX', category:'COUPE', size:'S', },
    { make:'Nissan', model: '240SX', category:'COUPE', size:'S', },
    { make:'Nissan', model: '300ZX', category:'COUPE', size:'M', },
    { make:'Nissan', model: '350Z', category:'COUPE', size:'M', },
    { make:'Nissan', model: '370Z', category:'COUPE', size:'M', },
    { make:'Nissan', model: 'Altima', category:'SEDAN', size:'M', },
    { make:'Nissan', model: 'Armada', category:'SUV', size:'E', },
    { make:'Nissan', model: 'Axxess', category:'MINIVAN', size:'L', },
    { make:'Nissan', model: 'Cube', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Frontier', category:'TRUCK', size:'L', },
    { make:'Nissan', model: 'GT-R', category:'EXOTIC', size:'E', },
    { make:'Nissan', model: 'Juke', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Kicks', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Leaf', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Maxima', category:'SEDAN', size:'M', },
    { make:'Nissan', model: 'Murano', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Murano CrossCabirolet', category:'SUV', size:'L', },
    { make:'Nissan', model: 'NV200', category:'MINIVAN', size:'E', },
    { make:'Nissan', model: 'Pathfinder', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Quest', category:'MINIVAN', size:'L', },
    { make:'Nissan', model: 'Rogue', category:'SUV', size:'L', },
    { make:'Nissan', model: 'Sentra', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Titan', category:'TRUCK', size:'E', },
    { make:'Nissan', model: 'Versa', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Versa Note', category:'SEDAN', size:'S', },
    { make:'Nissan', model: 'Xterra', category:'SUV', size:'L', },

    { make:'Noble', model: 'M10', category:'EXOTIC', size:'E', },
    { make:'Noble', model: 'M12', category:'EXOTIC', size:'E', },
    { make:'Noble', model: 'M400', category:'EXOTIC', size:'E', },

    
  ]);
};
