name: Back end test

on: [push, pull_request]

jobs:
  # test:
  #   name: test-runner
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: '12'
  #   - run: npm install
  coverage:
    # needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.5.4
        env:
          CC_TEST_REPORTER_ID: b4946cc9670a7efb590bd86a74d03bb077af95feeb64d78eced94b0c34a66cae
        with:
          coverageCommand: npm run coverage
          debug: true
