# This is a basic workflow to help you get started with Actions

name: Back end test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test-runner
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        node-version: '12'
    - run: npm install
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '12'
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.5.4
        env:
          CC_TEST_REPORTER_ID: b4946cc9670a7efb590bd86a74d03bb077af95feeb64d78eced94b0c34a66cae
        with: 
          coverageCommand: npm coverage          

